### PR TITLE
Fix: Information related to tokens in README

### PR DESCRIPTION
**Pull request by santunioni**
Fix documentation related to tokens. The secrets.GITHUB_TOKEN provided by the GitHub Actions App can do everything related to the repo if we [elevate its permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs), including calling workflow_dispatch and repository_dispatch.

Some people in my organization are using PAT's instead of the secrets.GITHUB_TOKEN when using this action because of the README suggestion, even when they are calling the same repository. Using PATs in that context provides unnecessary security risks.

### CODE REVIEW

**Comment by santunioni** [comment]
# Testing

1. Create two workflows:

---

`trigger.yaml`
```yaml
name: Trigger

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  repositorydispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: test-repo-dispatch
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
```

---

`triggered.yaml`
```yaml
name: Triggered

on:
  repository_dispatch:
    types: [test-repo-dispatch]

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require("fs")
            const eventPath = '${{ github.event_path }}' 
            fs.readFile(eventPath, "utf-8", (err, data) => {
              console.log(data)
              console.error(err)
            })
            return eventPath
```

---

2. Manually run the `Trigger` workflow
3. See the `Triggered` workflow will also run

**Comment by peter-evans** [comment]
@santunioni Thank you for this contribution! I wasn't aware of this token change.

I'm going to merge to a feature branch so I can make some further documentation and workflow changes. Then I'll merge to `main`.

**Comment by peter-evans** [comment]
I've updated the repo with your contribution. Thank you!

I also made `GITHUB_TOKEN` the default for input `token`. So you don't need to specify it anymore if your dispatch is local.

```yml
permissions:
  actions: write

jobs:
  repositorydispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: my-event
```

**Comment by peter-evans** [comment]
@santunioni I don't think elevating the token permissions is necessary. It seems to work without this:

```yml
permissions:
  actions: write
```

**Comment by santunioni** [comment]
@peter-evans great! It is even better this way. I assumed because we need `permissions.actions: write` for `workflow_dispatch` we would also need for `repository_dispatch`. Turns out I was wrong

**Comment by santunioni** [comment]
As an example, try this:
```
permissions:
  actions: none
```
which is now the default for GitHub Teams plan.

You will see the `trigger.yaml` fails.

**Comment by santunioni** [comment]
What approach do you think suits better the action? Telling the user the permission the workflow needs explicitly, without relying on GitHub defaults, or rely on the defaults?

**Comment by peter-evans** [comment]
Ah, interesting. In that case I will make a note of it in the readme in the same way I've done for other actions I maintain.

https://github.com/peter-evans/repository-dispatch/commit/cb18cc8cd6d1c954efb9f908614e9df982aac9cf

Thank you!

**Pull request merged**
